### ISSUE TITLE
Rich text fields spans conflict

### ISSUE THREAD

**Issue by phillysnow** [prismicio/prismic-vue#10]
When a rich text field has both a label and hyperlink on the same piece of text, the hyperlink will override the label and the label will not be applied as a span in the web application.

**Comment by CalebKester** [comment]
@phillysnow I'm dealing with this right now and I think I figured it out. Try replacing the following in your html-serializer:

```result = `<router-link to="${url}">${content}</router-link>`;```
to 
```result = `<router-link to="${url}">${children.join('')}</router-link>`;```

And any other places in the file where it uses content instead of children. See https://github.com/prismicio/prismic-dom/blob/master/src/richtext.js#L69

I'm still testing it a bit as I'm running into another error with "The client-side rendered virtual DOM tree is not matching server-rendered content. "

**Comment by lihbr** [comment]
Not an issue with this kit, closing!
