### ISSUE TITLE
noreferrer for external links

### ISSUE THREAD

**Issue by Kunsih6** [prismicio/prismic-vue#38]
Hello there!

I've noticed that the external links didn't include the attribute `rel = "noreferrer"` which is considered a good practice to avoid security and performance issues. More info about it [here](https://web.dev/external-anchors-use-rel-noopener/).

I'll create a PR that adds the attribute.

Thanks for your hard work!

**Comment by lihbr** [comment]
Hey @Kunsih6 thank you so much for your contributions!

We'll consider making the switch from `noopener` to `noreferrer` as it may have some unwanted side-effects for some users, not sure.

Also according to the documentation since `noreferrer` is a stronger alternative to `noopener` (also covering the `window.opener` case) it might no be needed to add both of them here: https://github.com/Kunsih6/prismic-vue/blob/master/src/components/Link.js#L44

**Comment by lihbr** [comment]
Hey, just leaving an update here, I still have this issue at the back of my mind, we'll consider it when working on our Vue 3 kit I think 🙂

**Comment by lihbr** [comment]
Hey @Kunsih6,

We discussed again this change with the team and ended up considering the performance issue was already handled by the `noopener` attribute value and that changing it to `noreferrer` might lead to some unexpected side effects. Therefore we might not change that value for this version of the kit.

We'll consider a way for people to pick their link strategy in the next major of this kit. Regarding that, we'll have RFCs and suggestion issues opened soon!

We're closing this issue and your PR for now but we're happy to reopen the discussion if you want to. Thank you so much for your interest in Prismic and willingness to contribute!
